MILVUS_URI = "http://localhost:19530"
COURSES_COLLECTION_NAME = "courses"
COLLECTION_NAME = "chat"
START_FIELD = "meta"
COLLECTIONS = [COLLECTION_NAME, COURSES_COLLECTION_NAME]
TEACHER_MAX = 4096

INSERT_BATCH_SIZE = 64
