COLLECTION_NAME = "example"
MILVUS_URI = "http://localhost:19530"
COURSES_COLLECTION_NAME = "courses"
START_FIELD = "meta"
COLLECTIONS = [COLLECTION_NAME, COURSES_COLLECTION_NAME]

INSERT_BATCH_SIZE = 64
